Repository Automattic/woocommerce-subscriptions-core, pull requests merged in 2021-12, with the labels that each got.

#55 Update tooltips used on the Payment Methods page to remove references to the Subscriptions Extension
  changelog.txt
  includes/admin/class-wc-subscriptions-admin.php
  includes/gateways/class-wc-subscriptions-core-payment-gateways.php
Labels: pr: ready to merge

#57 Pre-commit checks, adding simple unit testing & github actions
  .gitattributes
  .github/workflows/js-lint-test.yml
  .github/workflows/php-lint-test.yml
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  bin/install-wp-tests.sh
  bin/phpcs.sh
  bin/phpunit.sh
  bin/run-ci-tests.sh
  composer.json
  composer.lock
  lint-staged.config.js
  package-lock.json
  package.json
  phpcs.xml.dist
  phpunit.xml.dist
  tests/README.md
  tests/WP_UnitTestCase.php
  tests/unit/bootstrap.php
  tests/unit/test-class-simple-pass.php
Labels: pr: ready to merge

#65 Fix incorrect text when filtering subscriptions with no results
  changelog.txt
  includes/class-wc-subscriptions-core-plugin.php
Labels: pr: ready to merge

#70 Update recurring payments copy on payment gateways page
  changelog.txt
  includes/admin/class-wc-subscriptions-admin.php
Labels: pr: ready to merge

#56 Add JS validation to prevent users from creating free subscription products
  assets/js/admin/payment-method-restrictions.js
  changelog.txt
  includes/class-wc-subscriptions-core-plugin.php
  includes/gateways/class-wc-subscriptions-core-payment-gateways.php
  includes/gateways/class-wc-subscriptions-gateway-restrictions-manager.php
Labels: pr: ready to merge

#54 Update deprecated WooCommerce Blocks hook
  changelog.txt
  includes/class-wc-subscriptions-checkout.php
  includes/class-wcs-cart-renewal.php
Labels: type: task, size: small, pr: ready to merge

#72 Reduce the scope of the JS linting
  .eslintignore
  .prettierignore
  package.json
Labels: pr: needs review

#59 Update JS linting CI
  .eslintignore
  .eslintrc
  .github/workflows/js-lint-test.yml
  .prettierignore
  .prettierrc
  .stylelintrc.json
  assets/js/admin/admin-pointers.js
  assets/js/admin/admin.js
  assets/js/admin/meta-boxes-coupon.js
  assets/js/admin/meta-boxes-subscription.js
  assets/js/admin/wcs-meta-boxes-order.js
  assets/js/frontend/payment-methods.js
  assets/js/frontend/single-product.js
  assets/js/frontend/view-subscription.js
  assets/js/frontend/wcs-cart.js
  assets/js/modal.js
  assets/js/wcs-upgrade.js
  assets/src/js/filters/index.js
  assets/src/js/recurring-packages/index.js
  assets/src/js/recurring-totals/index.js
  assets/src/js/recurring-totals/index.scss
  assets/src/js/utils/index.js
  lint-staged.config.js
  package.json
  webpack.config.js
Labels: pr: ready to merge

#67 Introduce automated CSS linting
  .stylelintrc.json
  assets/css/about.css
  assets/css/admin-order-statuses.css
  assets/css/admin.css
  assets/css/checkout.css
  assets/css/modal.css
  assets/css/view-subscription.css
  assets/css/wcs-upgrade.css
  assets/src/js/recurring-totals/index.scss
  package-lock.json
  package.json
Labels: pr: ready to merge

#73 Issue/63 migrate admin coupons gateways unit tests
  tests/unit/admin/test-class-wcs-admin-post-types.php
  tests/unit/test-wcs-permalink-manager.php
Labels: pr: ready to merge

#77 CI: Migrate subscription unit tests
  includes/emails/class-wcs-email-new-switch-order.php
  tests/unit/helpers/class-phpunit-utils.php
  tests/unit/helpers/class-wcs-email-listener.php
  tests/unit/test-class-wc-subscriptions-payment-count.php
  tests/unit/test-class-wc-subscriptions.php
Labels: pr: ready to merge

#79 Revert package-lock.json file to ensure it's using `lockfileVersion: 2`
  package-lock.json
Labels: pr: needs review

#78 v1.3.0 release.
  build/index.asset.php
  build/index.js
  changelog.txt
  package-lock.json
  package.json
  woocommerce-subscriptions-core.php
Labels: pr: needs review

#80 Show the subscription fields when the product type is simple subscription
  assets/js/admin/admin.js
  changelog.txt
Labels: type: bug, pr: needs review, size: small
