Repository Automattic/woocommerce-subscriptions-core, pull requests merged in 2021-11, with the labels that each got.

#40 Prevent fatal errors caused by orders without a created date.
  changelog.txt
  includes/admin/meta-boxes/views/html-related-orders-row.php
Labels: pr: needs review

#41 Fix: Misleading order note on payment method change
  changelog.txt
  includes/class-wc-subscriptions-change-payment-gateway.php
Labels: pr: ready to merge

#44 adjust readme to clarify that this is a package
  README.md
Labels: pr: needs review

#46 Update tooltip wording when deleting product variation.
  changelog.txt
  includes/class-wc-subscriptions-product.php
Labels: pr: ready to merge

#49 Deprecate the admin error notice when downgrading subscriptions to a previous minor version
  changelog.txt
  includes/upgrades/class-wc-subscriptions-upgrader.php
Labels: pr: needs author reply, pr: ready to merge

#45 add explicit prompts to templates for product impact & tracking issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: needs review

#50 v1.2.0 release.
  changelog.txt
  composer.lock
  package-lock.json
  package.json
  woocommerce-subscriptions-core.php
Labels: pr: needs review

#53 Fixes minor deprecation issues in Subscriptions Core
  changelog.txt
  includes/class-wc-subscriptions-coupon.php
  includes/deprecated/deprecation-handlers/class-wc-subscriptions-deprecation-handler.php
Labels: priority: low, pr: ready to merge
