Repository Automattic/woocommerce-subscriptions-core, pull requests merged in 2022-04, with the labels that each got.

#132 Modify the changelog entry header format
  changelog.txt
Labels: pr: needs review

#140 Add support for unit tests in php8+
  .github/workflows/php-lint-test.yml
  bin/phpunit.sh
  bin/phpunit6
  changelog.txt
  composer.json
  composer.lock
  includes/class-wc-subscriptions-cart.php
  tests/WP_UnitTestCase.php
  tests/unit/abstracts/test-abstract-wcs-related-order-store.php
  tests/unit/data-stores/test-class-wcs-customer-store-cached-cpt.php
  tests/unit/data-stores/test-class-wcs-customer-store-cpt.php
  tests/unit/data-stores/test-class-wcs-related-order-store-cached-cpt.php
  tests/unit/data-stores/test-class-wcs-related-order-store-cpt.php
  tests/unit/test-class-wc-subscriptions-payment-count.php
  tests/unit/test-class-wc-subscriptions.php
  tests/unit/test-wcs-cart-functions.php
  tests/unit/test-wcs-core-autoloader.php
  tests/unit/test-wcs-deprecated-functions.php
  tests/unit/test-wcs-functions.php
  tests/unit/test-wcs-time-functions.php
  tests/unit/test-wcs-user-functions.php
Labels: pr: ready to merge

#133 Add GitHub workflow to automate release PRs
  .github/workflows/create-release-pr.yml
  bin/update-version.php
  package.json
Labels: pr: needs review

#136 Automate release tagging - #131
  .github/workflows/release.yml
Labels: type: enhancement, pr: needs review
