Repository Automattic/woocommerce-subscriptions-core, pull requests merged in 2022-05, with the labels that each got.

#159 Update `update_post_meta()` code where an order ID is passed to use CRUD
  includes/gateways/paypal/includes/class-wcs-paypal-standard-switcher.php
  includes/wcs-compatibility-functions.php
  tests/unit/test-class-wc-subscriptions.php
  tests/unit/test-wcs-compatibility-functions.php
Labels: compatibility

#161 Replace `get_posts()` with `wc_get_orders()` in WC_Subscriptions_Order::get_users_subscription_orders()
  includes/class-wc-subscriptions-order.php
Labels: pr: needs review

#165 Fix failed PHP 7.1 linting check
  .github/workflows/php-lint-test.yml
Labels: pr: needs review

#168 Replace any code using `get_post_type( $order_id )` with WC Data Store `get_order_type()`
  includes/admin/class-wcs-admin-meta-boxes.php
  includes/class-wc-subscriptions-manager.php
  includes/class-wcs-cart-renewal.php
  includes/wcs-helper-functions.php
  wcs-functions.php
Labels: compatibility: custom order tables

#173 Changelog for 2.0.0.
  changelog.txt
Labels: pr: needs review
