Repository Automattic/woocommerce-subscriptions-core, pull requests merged in 2022-12, with the labels that each got.

#317 [HPOS] Fix customers changing subscription addresses via My Account when HPOS is enabled
  changelog.txt
  includes/class-wc-subscriptions-addresses.php
  includes/wcs-compatibility-functions.php
Labels: pr: ready to merge

#312 Avoid getting a new instance of the subscription in `get_related_order_ids()` removes infinite loop potential
  changelog.txt
  includes/data-stores/class-wcs-related-order-store-cached-cpt.php
Labels: priority: low, pr: ready to merge

#318 Replace all remaining `get_post_type()`
  changelog.txt
  includes/admin/class-wcs-admin-post-types.php
  includes/class-wcs-cached-data-manager.php
  includes/class-wcs-download-handler.php
Labels: pr: ready to merge

#329 Add subscriptions-core version to SSR
  changelog.txt
  includes/admin/class-wcs-admin-system-status.php
Labels: pr: ready to merge

#331 Refactor `WC_Subscriptions_Renewal_Order::get_failed_order_replaced_by()` to support HPOS
  changelog.txt
  includes/class-wc-subscriptions-renewal-order.php
Labels: pr: ready to merge, compatibility: HPOS

#326 Add support for php8.2 in github action checks
  .github/workflows/php-lint-test.yml
Labels: pr: ready to merge

#347 [HPOS] Replace missing variable in WCS_Admin_Meta_Boxes::add_meta_boxes()
  includes/admin/class-wcs-admin-meta-boxes.php
Labels: pr: ready to merge, compatibility: HPOS

#332 Restore missing filters on Subscriptions listing.
  includes/admin/class-wcs-admin-post-types.php
Labels: pr: needs author reply

#349 Fixes updating all subscription payment methods when HPOS is enabled
  changelog.txt
  includes/class-wcs-payment-tokens.php
Labels: pr: ready to merge, compatibility: HPOS

#297 HPOS Admin UI support
  assets/css/admin.css
  assets/js/admin/meta-boxes-subscription.js
  changelog.txt
  includes/admin/class-wc-subscriptions-admin.php
  includes/admin/class-wcs-admin-meta-boxes.php
  includes/admin/class-wcs-admin-post-types.php
  includes/admin/meta-boxes/class-wcs-meta-box-schedule.php
  includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php
  includes/gateways/paypal/class-wcs-paypal.php
  includes/wcs-compatibility-functions.php
Labels: pr: needs review
