Repository Automattic/woocommerce-subscriptions-core, pull requests merged in 2022-03, with the labels that each got.

#119 Attach is purchasable limited product callbacks during checkout/cart block api requests
  changelog.txt
  includes/class-wcs-limiter.php
  includes/wcs-compatibility-functions.php
Labels: pr: needs review

#103 Fix: set up integration for Mini Cart Block and add new filter to compatible blocks.
  changelog.txt
  includes/class-wc-subscriptions-core-plugin.php
Labels: type: enhancement, pr: ready to merge

#115 Add missing elements and action in recurring shipping packages
  changelog.txt
  includes/wcs-cart-functions.php
Labels: pr: ready to merge

#121 Remove the resubscribe relationship from the subscriptions that get anonymized
  changelog.txt
  includes/privacy/class-wcs-privacy-background-updater.php
Labels: pr: needs review

#125 Fix i18n issue with strings that appear on the My account > Payment methods page.
  changelog.txt
  includes/class-wcs-my-account-payment-methods.php
Labels: pr: needs review, category: i18n

#124 Blocks Integration: Switch to global functions to remove deprecation warnings
  changelog.txt
  includes/class-wc-subscriptions-extend-store-endpoint.php
  includes/class-wcs-cart-renewal.php
Labels: pr: needs review, type: task
