Repository Automattic/woocommerce-subscriptions-core, pull requests merged in 2022-11, with the labels that each got.

#235 Fix get_items() on null error in Synchroniser when purchasing subscription with HPOS & Syncing to CPT enabled
  changelog.txt
  includes/class-wc-subscriptions-synchroniser.php
Labels: pr: ready to merge

#233 Mark wcs_get_objects_property as deprecated
  changelog.txt
  includes/wcs-compatibility-functions.php
Labels: pr: ready to merge

#229 Refactor wcs_copy_meta for it to work with HPOS environments
  changelog.txt
  includes/class-wc-subscriptions-data-copier.php
  includes/wcs-order-functions.php
  tests/unit/test-class-wc-subscriptions-data-copier.php
Labels: pr: needs review, compatibility: custom order tables

#171 Replace code that uses get_posts() with wc_get_orders()
  changelog.txt
  includes/admin/class-wcs-admin-post-types.php
  includes/gateways/paypal/class-wcs-paypal.php
  includes/gateways/paypal/includes/class-wcs-paypal-standard-ipn-handler.php
  includes/wcs-order-functions.php
  tests/unit/test-wcs-functions.php
  tests/unit/test-wcs-order-functions.php
  tests/unit/test-wcs-paypal-functions.php
  wcs-functions.php
Labels: pr: ready to merge, compatibility: HPOS

#254 Update naming of library version getter.
  bin/update-version.php
  changelog.txt
  includes/admin/class-wc-subscriptions-admin.php
  includes/admin/class-wcs-admin-meta-boxes.php
  includes/class-wc-subscriptions-core-plugin.php
  includes/class-wc-subscriptions-frontend-scripts.php
  includes/class-wcs-blocks-integration.php
  includes/class-wcs-modal.php
  includes/class-wcs-my-account-payment-methods.php
  includes/gateways/paypal/class-wcs-paypal.php
  includes/upgrades/class-wc-subscriptions-upgrader.php
  package.json
Labels: pr: ready to merge

#252 Refactor the save dates datastore function and backfill dates when syncing is enabled
  changelog.txt
  includes/data-stores/class-wcs-orders-table-subscription-data-store.php
  includes/data-stores/class-wcs-subscription-data-store-cpt.php
Labels: pr: ready to merge, compatibility: HPOS

#256 Refactor our Related Orders Data Store classes to support WC CRUD methods
  changelog.txt
  includes/data-stores/class-wcs-orders-table-subscription-data-store.php
  includes/data-stores/class-wcs-related-order-store-cached-cpt.php
  includes/data-stores/class-wcs-related-order-store-cpt.php
  includes/data-stores/class-wcs-subscription-data-store-cpt.php
  tests/unit/data-stores/test-class-wcs-related-order-store-cached-cpt.php
Labels: pr: needs review

#272 Fix infinite loops on HPOS environments
  changelog.txt
  includes/data-stores/class-wcs-orders-table-subscription-data-store.php
Labels: pr: needs review

#258 Enable customers to purchase a subscription using WCPay and HPOS tables
  changelog.txt
  includes/class-wc-subscription.php
  includes/class-wc-subscriptions-order.php
  includes/data-stores/class-wcs-orders-table-subscription-data-store.php
  includes/wcs-order-functions.php
  tests/unit/test-class-wc-subscriptions.php
Labels: pr: needs review

#280 Fix PHPCS errors and warnings in metabox-related files to improve code quality
  includes/admin/class-wcs-admin-meta-boxes.php
  includes/admin/meta-boxes/class-wcs-meta-box-schedule.php
  includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php
Labels: type: task, pr: ready to merge

#275 When copying payment token meta, set it in a CRUD compatible way
  changelog.txt
  includes/class-wc-subscriptions-data-copier.php
Labels: pr: ready to merge

#286 Fix HPOS renewal order payments - copy tokens between orders and subscriptions inside the copier class
  changelog.txt
  includes/class-wc-subscriptions-data-copier.php
Labels: pr: needs review, compatibility: HPOS

#292 [HPOS] Refactor `wcs_is_subscription` helper function to support HPOS
  changelog.txt
  wcs-functions.php
Labels: pr: ready to merge

#290 Fix renewal orders on HPOS having no items on the returned order instance
  changelog.txt
  includes/wcs-order-functions.php
Labels: pr: needs review, compatibility: HPOS

#253 Display related orders table when viewing the new "Edit Order" page (HPOS enabled stores)
  changelog.txt
  includes/admin/class-wc-subscriptions-admin.php
  includes/admin/class-wcs-admin-meta-boxes.php
  includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php
  includes/admin/meta-boxes/views/html-related-orders-row.php
  includes/admin/meta-boxes/views/html-related-orders-table.php
Labels: compatibility: HPOS

#269 Use CRUD method to get edit order URL in related orders metabox
  changelog.txt
  includes/admin/meta-boxes/views/html-related-orders-row.php
Labels: compatibility: HPOS

#282 [HPOS] Refactor `WCS_Meta_Box_Schedule::save` to fix PHP notices that occur when updating an order via the Edit Order page
  changelog.txt
  includes/admin/meta-boxes/class-wcs-meta-box-schedule.php
Labels: pr: needs review

#303 Backfill our related orders meta saved on orders when HPOS and data syncing is enabled
  changelog.txt
  includes/data-stores/class-wcs-related-order-store-cpt.php
Labels: pr: ready to merge

#305 Remove all get_post_type() from WC_Subscriptions_Manager.
  changelog.txt
  includes/class-wc-subscriptions-manager.php
Labels: pr: ready to merge

#281 [HPOS] Refactor `WCS_Meta_Box_Subscription_Data::save` to fix PHP notices that occur when updating an order via the Edit Order page
  changelog.txt
  includes/admin/class-wcs-admin-meta-boxes.php
  includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php
Labels: pr: ready to merge
