Repository Automattic/woocommerce-subscriptions-core, pull requests merged in 2023-01, with the labels that each got.

#356 [HPOS] Fix filtering the Amin Orders table by subscription related orders
  changelog.txt
  includes/admin/class-wc-subscriptions-admin.php
  includes/admin/class-wcs-admin-post-types.php
Labels: pr: needs review

#359 Check if WooCommerce is older than 7.3 in `wcs_get_page_screen_id()`.
  includes/wcs-compatibility-functions.php
Labels: pr: needs review

#357 [HPOS] Fix "ID on non-object" errors on the edit subscription screen
  changelog.txt
  includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php
  includes/admin/meta-boxes/views/html-subscription-schedule.php
  includes/wcs-compatibility-functions.php
Labels: pr: ready to merge

#336 Prevent a post record re-sync on every subscription get
  changelog.txt
  includes/data-stores/class-wcs-orders-table-subscription-data-store.php
Labels: pr: needs review, compatibility: HPOS

#350 Fix/replace post hooks manager class
  changelog.txt
  includes/class-wc-subscriptions-manager.php
  includes/data-stores/class-wcs-orders-table-subscription-data-store.php
Labels: pr: needs review, compatibility: HPOS

#360 [HPOS] Allow admins to filter the Subscriptions List Table when HPOS is enabled.
  changelog.txt
  includes/admin/class-wcs-admin-post-types.php
  wcs-functions.php
Labels: pr: ready to merge

#365 [HPOS] Replace remaining delete post code in subscriptions to use CRUD methods/hooks
  changelog.txt
  includes/class-wc-subscriptions-checkout.php
  includes/class-wc-subscriptions-manager.php
  includes/class-wcs-download-handler.php
Labels: pr: ready to merge

#362 Fix missing start date errors on new subscriptions for the schedule metabox
  changelog.txt
  includes/admin/meta-boxes/class-wcs-meta-box-schedule.php
Labels: pr: ready to merge

#369 Reorder the subscription line items metabox on hpos environments
  changelog.txt
  includes/admin/class-wcs-admin-meta-boxes.php
Labels: pr: ready to merge, compatibility: HPOS

#367 Refactor and update the admin subscription bulk action handling to support HPOS environments
  changelog.txt
  includes/admin/class-wcs-admin-post-types.php
Labels: pr: ready to merge, compatibility: HPOS

#378 Fix parent order link in subscription details box on subscription admin edit page
  changelog.txt
  includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php
Labels: pr: needs review, compatibility: HPOS

#379 Fix link to subscription or order in admin notice from failed scheduled actions
  changelog.txt
  includes/class-wcs-failed-scheduled-action-manager.php
Labels: pr: ready to merge, compatibility: HPOS, category: projects

#372 [HPOS] Show Subscription status filters above list table when HPOS is enabled
  changelog.txt
  includes/admin/class-wcs-admin-post-types.php
  includes/data-stores/class-wcs-orders-table-subscription-data-store.php
  includes/data-stores/class-wcs-subscription-data-store-cpt.php
Labels: pr: ready to merge, compatibility: HPOS

#373 Update WCS_Related_Order_Store_Cached_CPT to use an object cache manager on HPOS environments
  changelog.txt
  includes/class-wcs-object-data-cache-manager.php
  includes/data-stores/class-wcs-related-order-store-cached-cpt.php
Labels: pr: ready to merge, compatibility: HPOS

#374 Refactor WC_Subscriptions_Tracker to support HPOS
  changelog.txt
  includes/class-wc-subscriptions-tracker.php
Labels: pr: needs review, compatibility: HPOS

#381 [HPOS] Fixes the Cancel and remove personal data subscription bulk action on HPOS stores.
  assets/js/admin/admin.js
  includes/admin/class-wc-subscriptions-admin.php
  includes/admin/class-wcs-admin-post-types.php
  includes/privacy/class-wcs-privacy.php
Labels: pr: ready to merge, compatibility: HPOS

#386 Fix "Subscriptions by Payment Gateway" in WC → Status when HPOS is enabled
  changelog.txt
  includes/admin/class-wcs-admin-system-status.php
Labels: pr: ready to merge, compatibility: HPOS, category: projects

#387 Fix PHPCS violations in `WCS_Admin_System_Status` to improve code quality
  changelog.txt
  includes/admin/class-wcs-admin-system-status.php
Labels: type: task, priority: low, category: refactor, pr: ready to merge

#377 Fix PHPCS violations in `WC_Subscriptions_Tracker` to improve code quality
  changelog.txt
  includes/class-wc-subscriptions-tracker.php
Labels: type: task, priority: low, category: refactor, pr: ready to merge

#389 Introduces new handling for trash, delete and untrash subscription bulk actions
  includes/admin/class-wcs-admin-post-types.php
Labels: pr: needs review, compatibility: HPOS

#383 Update cache when subscription is trashed, deleted, or untrashed
  changelog.txt
  includes/class-wcs-object-data-cache-manager.php
Labels: pr: needs review, compatibility: HPOS

#354 Highlight overdue/late payments in admin subscriptions list
  assets/css/admin.css
  changelog.txt
  includes/admin/class-wcs-admin-post-types.php
Labels: pr: needs review

#179 Fix: use shipping address at checkout when renewing, resubscribing or switching subscriptions
  changelog.txt
  includes/class-wc-subscriptions-checkout.php
  includes/class-wcs-cart-renewal.php
  includes/wcs-helper-functions.php
  tests/unit/test-wcs-helper-functions.php
Labels: pr: ready to merge

#395 Ensure update_all_payment_methods_from_subscription() function call receives the latest version of the subscription after a payment method change
  changelog.txt
  includes/class-wc-subscriptions-change-payment-gateway.php
Labels: pr: ready to merge
